# Generated by Django 3.2.7 on 2021-09-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('locality', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pin', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('West Bengal', 'West Bengal'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttrakhand', 'Uttrakhand'), ('Tamil Nadu', 'Tamil Nadu'), ('Sikkim', 'Sikkim'), ('Telangna', 'Telangna'), ('Rajasthan', 'Rajasthan'), ('Punjab', 'Punjab'), ('Maharastra', 'Maharastra'), ('Bay Of Bengal', 'Bay Of Bengal'), ('Madhya Pradesh', 'Madhya Pradesh')], max_length=50)),
                ('mobile', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('job_city', models.CharField(max_length=50)),
                ('profile_image', models.ImageField(blank=True, upload_to='profileimg')),
                ('my_file', models.FileField(blank=True, upload_to='doc')),
            ],
        ),
    ]
